### ISSUE TITLE
Issue with deck:latest

### ISSUE THREAD

**Issue by dberuben** [kenzanlabs/spinikube#13]
Hi,

Its look like the version of deck:latest doesn't work,
we rollback the version to v2.738.0 and its working well.

**Comment by willgorman** [comment]
I think I may be having the same problem.  The deck app only shows the initial logo animation and never gets past that.  How did you switch to version v2.783.0?  I tried updating the spinnaker-deck jenkins job to `docker run -v `pwd`/webpack:/opt/webpack quay.io/spinnaker/deck:v2.783.0 bash -c "npm install; npm run build; mv -v build/webpack/* /opt/webpack"`,  ran the build again and then ran refresh.py but I still ended up with the same problem.

**Comment by dberuben** [comment]
@willgorman
First update the job

 `docker run -vpwd/webpack:/opt/webpack quay.io/spinnaker/**deck:v2.738.0** bash -c "npm install; npm run build; mv -v build/webpack/* /opt/webpack"`

When all pods are running go to jenkins interface and run the deck jenkins job again,
it should update your local repo with the old deck version, and for finish you have to delete the deck pods to rebuild the new version. 

i push some modifications in my own repo, you can clone it
