### ISSUE TITLE
Include Apache 2.0 license

### ISSUE THREAD

**Issue by paul-barry-kenzan** [kenzanlabs/spinikube#22]
As part of the kenzanlabs initiative of ensuring all repositories are following expected licensing guidelines for Kenzan, an [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/) should be included within this project repo.

Including a license will require:
- [x] A LICENSE.md file be added to the repo
- [x] A License footer be added to the README ([License footer example](https://projects.kenzan.com/confluence/display/KKNOW/Producer+Policies#ProducerPolicies-Licensing))

**Comment by paul-barry-kenzan** [comment]
@patrickthesailorman 
As you work through the issues, could you check the tasks in the description? Hoping to track that each repo has both parts of the license. Thanks.

**Comment by thescientist13** [comment]
I got you!  ✅
